[ERROR 2016-11-19 09:27:29,448 @ 2368] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 134, in group_post
    ret=globals()[request.POST.get('type')](request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 102, in group_update
    ddata=json.loads(request.POST.get('newarray'))
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[ERROR 2016-11-19 09:30:08,970 @ 26840] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 134, in group_post
    ret=globals()[request.POST.get('type')](request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 102, in group_update
    ddata=json.loads(request.POST.get('newarray',[]))
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[ERROR 2016-11-19 09:30:43,753 @ 11880] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 134, in group_post
    ret=globals()[request.POST.get('type')](request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 102, in group_update
    ddata=json.loads(request.POST.get('newarray',None))
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[ERROR 2016-11-19 09:31:09,391 @ 21308] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 134, in group_post
    ret=globals()[request.POST.get('type')](request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 123, in group_update
    ret['status'] = e[1]
IndexError: tuple index out of range
[ERROR 2016-11-19 09:31:22,144 @ 21308] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 134, in group_post
    ret=globals()[request.POST.get('type')](request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 123, in group_update
    ret['status'] = e[1]
IndexError: tuple index out of range
[ERROR 2016-11-19 09:31:50,973 @ 22504] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 135, in group_post
    ret=globals()[request.POST.get('type')](request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 124, in group_update
    ret['status'] = e[1]
IndexError: tuple index out of range
[ERROR 2016-11-19 09:32:34,618 @ 19624] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 135, in group_post
    ret=globals()[request.POST.get('type')](request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 124, in group_update
    ret['status'] = e[1]
IndexError: tuple index out of range
[ERROR 2016-11-19 09:33:49,915 @ 21384] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 29, in post
    return packageResponse(ret)
  File "D:\work\redjango\Management\Cmdb\methods\common.py", line 12, in packageResponse
    json_status = json.dumps(json_status)
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AttributeError("'AssetGroup' object has no attribute 'update'",) is not JSON serializable
[DEBUG 2016-11-19 09:52:18,753 @ 16524] - CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:19,476 @ 16524] - CREATE TABLE `Cmdb_asset` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `ip` varchar(32) NULL, `other_ip` varchar(255) NULL, `hostname` varchar(128) NOT NULL UNIQUE, `port` integer NULL, `username` varchar(16) NULL, `password` varchar(256) NULL, `use_default_auth` bool NOT NULL, `mac` varchar(20) NULL, `remote_ip` varchar(16) NULL, `brand` varchar(64) NULL, `cpu` varchar(64) NULL, `memory` varchar(128) NULL, `disk` varchar(1024) NULL, `system_type` varchar(32) NULL, `system_version` varchar(8) NULL, `system_arch` varchar(16) NULL, `cabinet` varchar(32) NULL, `position` integer NULL, `number` varchar(32) NULL, `status` integer NULL, `asset_type` integer NULL, `env` integer NULL, `sn` varchar(128) NULL, `date_added` datetime NULL, `is_active` bool NOT NULL, `comment` varchar(128) NULL); (params None)
[DEBUG 2016-11-19 09:52:21,753 @ 16524] - CREATE TABLE `Cmdb_assetgroup` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE, `comment` varchar(160) NULL); (params None)
[DEBUG 2016-11-19 09:52:21,773 @ 16524] - CREATE TABLE `Cmdb_assetrecord` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `username` varchar(30) NULL, `alert_time` datetime NOT NULL, `content` longtext NULL, `comment` longtext NULL, `asset_id` integer NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:21,789 @ 16524] - CREATE TABLE `Cmdb_idc` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(32) NOT NULL, `bandwidth` varchar(32) NULL, `linkman` varchar(16) NULL, `phone` varchar(32) NULL, `address` varchar(128) NULL, `network` longtext NULL, `date_added` date NULL, `operator` varchar(32) NULL, `comment` varchar(128) NULL); (params None)
[DEBUG 2016-11-19 09:52:21,805 @ 16524] - CREATE TABLE `Cmdb_asset_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `asset_id` integer NOT NULL, `assetgroup_id` integer NOT NULL, UNIQUE (`asset_id`, `assetgroup_id`)); (params None)
[DEBUG 2016-11-19 09:52:21,818 @ 16524] - ALTER TABLE `Cmdb_asset` ADD COLUMN `idc_id` integer NULL; (params [])
[DEBUG 2016-11-19 09:52:21,819 @ 16524] - ALTER TABLE `Cmdb_asset` ALTER COLUMN `idc_id` DROP DEFAULT; (params [])
[DEBUG 2016-11-19 09:52:21,822 @ 16524] - ALTER TABLE `Cmdb_assetrecord` ADD CONSTRAINT `Cmdb_assetrecord_asset_id_19e1e7bf_fk_Cmdb_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `Cmdb_asset` (`id`); (params [])
[DEBUG 2016-11-19 09:52:21,832 @ 16524] - CREATE INDEX `Cmdb_assetrecord_51c6d5db` ON `Cmdb_assetrecord` (`asset_id`); (params [])
[DEBUG 2016-11-19 09:52:21,834 @ 16524] - ALTER TABLE `Cmdb_asset_group` ADD CONSTRAINT `Cmdb_asset_group_asset_id_34905f0_fk_Cmdb_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `Cmdb_asset` (`id`); (params [])
[DEBUG 2016-11-19 09:52:21,835 @ 16524] - ALTER TABLE `Cmdb_asset_group` ADD CONSTRAINT `Cmdb_asset_group_assetgroup_id_768ad676_fk_Cmdb_assetgroup_id` FOREIGN KEY (`assetgroup_id`) REFERENCES `Cmdb_assetgroup` (`id`); (params [])
[DEBUG 2016-11-19 09:52:21,838 @ 16524] - CREATE INDEX `Cmdb_asset_group_51c6d5db` ON `Cmdb_asset_group` (`asset_id`); (params [])
[DEBUG 2016-11-19 09:52:21,839 @ 16524] - CREATE INDEX `Cmdb_asset_group_2f088294` ON `Cmdb_asset_group` (`assetgroup_id`); (params [])
[DEBUG 2016-11-19 09:52:21,842 @ 16524] - CREATE INDEX `Cmdb_asset_0869e37a` ON `Cmdb_asset` (`idc_id`); (params [])
[DEBUG 2016-11-19 09:52:21,845 @ 16524] - ALTER TABLE `Cmdb_asset` ADD CONSTRAINT `Cmdb_asset_idc_id_71aeb26e_fk_Cmdb_idc_id` FOREIGN KEY (`idc_id`) REFERENCES `Cmdb_idc` (`id`); (params [])
[DEBUG 2016-11-19 09:52:21,852 @ 16524] - CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:21,878 @ 16524] - ALTER TABLE `django_content_type` ADD CONSTRAINT `django_content_type_app_label_3ec8c61c_uniq` UNIQUE (`app_label`, `model`); (params [])
[DEBUG 2016-11-19 09:52:21,885 @ 16524] - CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL, UNIQUE (`content_type_id`, `codename`)); (params None)
[DEBUG 2016-11-19 09:52:21,930 @ 16524] - CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); (params None)
[DEBUG 2016-11-19 09:52:21,970 @ 16524] - CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL, UNIQUE (`group_id`, `permission_id`)); (params None)
[DEBUG 2016-11-19 09:52:22,002 @ 16524] - CREATE TABLE `auth_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime NOT NULL, `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(75) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:22,006 @ 16524] - CREATE TABLE `auth_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL, UNIQUE (`user_id`, `group_id`)); (params None)
[DEBUG 2016-11-19 09:52:22,085 @ 16524] - CREATE TABLE `auth_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL, UNIQUE (`user_id`, `permission_id`)); (params None)
[DEBUG 2016-11-19 09:52:22,092 @ 16524] - ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permissi_content_type_id_51277a81_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
[DEBUG 2016-11-19 09:52:22,101 @ 16524] - CREATE INDEX `auth_permission_417f1b1c` ON `auth_permission` (`content_type_id`); (params [])
[DEBUG 2016-11-19 09:52:22,107 @ 16524] - ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_58c48ba9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
[DEBUG 2016-11-19 09:52:22,111 @ 16524] - ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissi_permission_id_23962d04_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
[DEBUG 2016-11-19 09:52:22,115 @ 16524] - CREATE INDEX `auth_group_permissions_0e939a4f` ON `auth_group_permissions` (`group_id`); (params [])
[DEBUG 2016-11-19 09:52:22,118 @ 16524] - CREATE INDEX `auth_group_permissions_8373b171` ON `auth_group_permissions` (`permission_id`); (params [])
[DEBUG 2016-11-19 09:52:22,121 @ 16524] - ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_24702650_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
[DEBUG 2016-11-19 09:52:22,125 @ 16524] - ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_group_id_30a071c9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
[DEBUG 2016-11-19 09:52:22,128 @ 16524] - CREATE INDEX `auth_user_groups_e8701ad4` ON `auth_user_groups` (`user_id`); (params [])
[DEBUG 2016-11-19 09:52:22,130 @ 16524] - CREATE INDEX `auth_user_groups_0e939a4f` ON `auth_user_groups` (`group_id`); (params [])
[DEBUG 2016-11-19 09:52:22,132 @ 16524] - ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_7cd7acb6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
[DEBUG 2016-11-19 09:52:22,134 @ 16524] - ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_perm_permission_id_3d7071f0_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
[DEBUG 2016-11-19 09:52:22,138 @ 16524] - CREATE INDEX `auth_user_user_permissions_e8701ad4` ON `auth_user_user_permissions` (`user_id`); (params [])
[DEBUG 2016-11-19 09:52:22,141 @ 16524] - CREATE INDEX `auth_user_user_permissions_8373b171` ON `auth_user_user_permissions` (`permission_id`); (params [])
[DEBUG 2016-11-19 09:52:22,154 @ 16524] - CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime NOT NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL, `change_message` longtext NOT NULL, `content_type_id` integer NULL, `user_id` integer NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:22,158 @ 16524] - ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin__content_type_id_5151027a_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
[DEBUG 2016-11-19 09:52:22,160 @ 16524] - ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_user_id_1c5f563_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
[DEBUG 2016-11-19 09:52:22,163 @ 16524] - CREATE INDEX `django_admin_log_417f1b1c` ON `django_admin_log` (`content_type_id`); (params [])
[DEBUG 2016-11-19 09:52:22,164 @ 16524] - CREATE INDEX `django_admin_log_e8701ad4` ON `django_admin_log` (`user_id`); (params [])
[DEBUG 2016-11-19 09:52:22,184 @ 16524] - ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; (params [])
[DEBUG 2016-11-19 09:52:22,197 @ 16524] - ALTER TABLE `django_content_type` DROP COLUMN `name` CASCADE; (params [])
[DEBUG 2016-11-19 09:52:22,210 @ 16524] - ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; (params [])
[DEBUG 2016-11-19 09:52:22,221 @ 16524] - ALTER TABLE `auth_user` MODIFY `email` varchar(254) NOT NULL; (params [])
[DEBUG 2016-11-19 09:52:22,244 @ 16524] - ALTER TABLE `auth_user` MODIFY `last_login` datetime NULL; (params [])
[DEBUG 2016-11-19 09:52:22,253 @ 16524] - CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:22,256 @ 16524] - CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date`); (params [])
[DEBUG 2016-11-19 09:52:31,707 @ 16000] - CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:34,063 @ 16000] - CREATE TABLE `Cmdb_asset` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `ip` varchar(32) NULL, `other_ip` varchar(255) NULL, `hostname` varchar(128) NOT NULL UNIQUE, `port` integer NULL, `username` varchar(16) NULL, `password` varchar(256) NULL, `use_default_auth` bool NOT NULL, `mac` varchar(20) NULL, `remote_ip` varchar(16) NULL, `brand` varchar(64) NULL, `cpu` varchar(64) NULL, `memory` varchar(128) NULL, `disk` varchar(1024) NULL, `system_type` varchar(32) NULL, `system_version` varchar(8) NULL, `system_arch` varchar(16) NULL, `cabinet` varchar(32) NULL, `position` integer NULL, `number` varchar(32) NULL, `status` integer NULL, `asset_type` integer NULL, `env` integer NULL, `sn` varchar(128) NULL, `date_added` datetime NULL, `is_active` bool NOT NULL, `comment` varchar(128) NULL); (params None)
[DEBUG 2016-11-19 09:52:34,201 @ 16000] - CREATE TABLE `Cmdb_assetgroup` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE, `comment` varchar(160) NULL); (params None)
[DEBUG 2016-11-19 09:52:34,217 @ 16000] - CREATE TABLE `Cmdb_assetrecord` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `username` varchar(30) NULL, `alert_time` datetime NOT NULL, `content` longtext NULL, `comment` longtext NULL, `asset_id` integer NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:34,230 @ 16000] - CREATE TABLE `Cmdb_idc` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(32) NOT NULL, `bandwidth` varchar(32) NULL, `linkman` varchar(16) NULL, `phone` varchar(32) NULL, `address` varchar(128) NULL, `network` longtext NULL, `date_added` date NULL, `operator` varchar(32) NULL, `comment` varchar(128) NULL); (params None)
[DEBUG 2016-11-19 09:52:34,243 @ 16000] - CREATE TABLE `Cmdb_asset_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `asset_id` integer NOT NULL, `assetgroup_id` integer NOT NULL, UNIQUE (`asset_id`, `assetgroup_id`)); (params None)
[DEBUG 2016-11-19 09:52:34,259 @ 16000] - ALTER TABLE `Cmdb_asset` ADD COLUMN `idc_id` integer NULL; (params [])
[DEBUG 2016-11-19 09:52:34,263 @ 16000] - ALTER TABLE `Cmdb_asset` ALTER COLUMN `idc_id` DROP DEFAULT; (params [])
[DEBUG 2016-11-19 09:52:34,266 @ 16000] - ALTER TABLE `Cmdb_assetrecord` ADD CONSTRAINT `Cmdb_assetrecord_asset_id_19e1e7bf_fk_Cmdb_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `Cmdb_asset` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,269 @ 16000] - CREATE INDEX `Cmdb_assetrecord_51c6d5db` ON `Cmdb_assetrecord` (`asset_id`); (params [])
[DEBUG 2016-11-19 09:52:34,272 @ 16000] - ALTER TABLE `Cmdb_asset_group` ADD CONSTRAINT `Cmdb_asset_group_asset_id_34905f0_fk_Cmdb_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `Cmdb_asset` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,273 @ 16000] - ALTER TABLE `Cmdb_asset_group` ADD CONSTRAINT `Cmdb_asset_group_assetgroup_id_768ad676_fk_Cmdb_assetgroup_id` FOREIGN KEY (`assetgroup_id`) REFERENCES `Cmdb_assetgroup` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,276 @ 16000] - CREATE INDEX `Cmdb_asset_group_51c6d5db` ON `Cmdb_asset_group` (`asset_id`); (params [])
[DEBUG 2016-11-19 09:52:34,279 @ 16000] - CREATE INDEX `Cmdb_asset_group_2f088294` ON `Cmdb_asset_group` (`assetgroup_id`); (params [])
[DEBUG 2016-11-19 09:52:34,282 @ 16000] - CREATE INDEX `Cmdb_asset_0869e37a` ON `Cmdb_asset` (`idc_id`); (params [])
[DEBUG 2016-11-19 09:52:34,283 @ 16000] - ALTER TABLE `Cmdb_asset` ADD CONSTRAINT `Cmdb_asset_idc_id_71aeb26e_fk_Cmdb_idc_id` FOREIGN KEY (`idc_id`) REFERENCES `Cmdb_idc` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,295 @ 16000] - CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:34,302 @ 16000] - ALTER TABLE `django_content_type` ADD CONSTRAINT `django_content_type_app_label_3ec8c61c_uniq` UNIQUE (`app_label`, `model`); (params [])
[DEBUG 2016-11-19 09:52:34,313 @ 16000] - CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL, UNIQUE (`content_type_id`, `codename`)); (params None)
[DEBUG 2016-11-19 09:52:34,341 @ 16000] - CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); (params None)
[DEBUG 2016-11-19 09:52:34,344 @ 16000] - CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL, UNIQUE (`group_id`, `permission_id`)); (params None)
[DEBUG 2016-11-19 09:52:34,352 @ 16000] - CREATE TABLE `auth_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime NOT NULL, `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(75) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:34,355 @ 16000] - CREATE TABLE `auth_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL, UNIQUE (`user_id`, `group_id`)); (params None)
[DEBUG 2016-11-19 09:52:34,358 @ 16000] - CREATE TABLE `auth_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL, UNIQUE (`user_id`, `permission_id`)); (params None)
[DEBUG 2016-11-19 09:52:34,361 @ 16000] - ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permissi_content_type_id_51277a81_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,361 @ 16000] - CREATE INDEX `auth_permission_417f1b1c` ON `auth_permission` (`content_type_id`); (params [])
[DEBUG 2016-11-19 09:52:34,364 @ 16000] - ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_58c48ba9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,365 @ 16000] - ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissi_permission_id_23962d04_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,367 @ 16000] - CREATE INDEX `auth_group_permissions_0e939a4f` ON `auth_group_permissions` (`group_id`); (params [])
[DEBUG 2016-11-19 09:52:34,368 @ 16000] - CREATE INDEX `auth_group_permissions_8373b171` ON `auth_group_permissions` (`permission_id`); (params [])
[DEBUG 2016-11-19 09:52:34,369 @ 16000] - ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_24702650_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,371 @ 16000] - ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_group_id_30a071c9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,371 @ 16000] - CREATE INDEX `auth_user_groups_e8701ad4` ON `auth_user_groups` (`user_id`); (params [])
[DEBUG 2016-11-19 09:52:34,374 @ 16000] - CREATE INDEX `auth_user_groups_0e939a4f` ON `auth_user_groups` (`group_id`); (params [])
[DEBUG 2016-11-19 09:52:34,375 @ 16000] - ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_7cd7acb6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,377 @ 16000] - ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_perm_permission_id_3d7071f0_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,378 @ 16000] - CREATE INDEX `auth_user_user_permissions_e8701ad4` ON `auth_user_user_permissions` (`user_id`); (params [])
[DEBUG 2016-11-19 09:52:34,380 @ 16000] - CREATE INDEX `auth_user_user_permissions_8373b171` ON `auth_user_user_permissions` (`permission_id`); (params [])
[DEBUG 2016-11-19 09:52:34,391 @ 16000] - CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime NOT NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL, `change_message` longtext NOT NULL, `content_type_id` integer NULL, `user_id` integer NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:34,392 @ 16000] - ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin__content_type_id_5151027a_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,394 @ 16000] - ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_user_id_1c5f563_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
[DEBUG 2016-11-19 09:52:34,397 @ 16000] - CREATE INDEX `django_admin_log_417f1b1c` ON `django_admin_log` (`content_type_id`); (params [])
[DEBUG 2016-11-19 09:52:34,398 @ 16000] - CREATE INDEX `django_admin_log_e8701ad4` ON `django_admin_log` (`user_id`); (params [])
[DEBUG 2016-11-19 09:52:34,417 @ 16000] - ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; (params [])
[DEBUG 2016-11-19 09:52:34,430 @ 16000] - ALTER TABLE `django_content_type` DROP COLUMN `name` CASCADE; (params [])
[DEBUG 2016-11-19 09:52:34,443 @ 16000] - ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; (params [])
[DEBUG 2016-11-19 09:52:34,454 @ 16000] - ALTER TABLE `auth_user` MODIFY `email` varchar(254) NOT NULL; (params [])
[DEBUG 2016-11-19 09:52:34,477 @ 16000] - ALTER TABLE `auth_user` MODIFY `last_login` datetime NULL; (params [])
[DEBUG 2016-11-19 09:52:34,486 @ 16000] - CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime NOT NULL); (params None)
[DEBUG 2016-11-19 09:52:34,487 @ 16000] - CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date`); (params [])
[DEBUG 2016-11-19 10:01:21,049 @ 23056] - CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime NOT NULL); (params None)
[DEBUG 2016-11-19 10:01:26,055 @ 23056] - CREATE TABLE `Cmdb_asset` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `ip` varchar(32) NULL, `other_ip` varchar(255) NULL, `hostname` varchar(128) NOT NULL UNIQUE, `port` integer NULL, `username` varchar(16) NULL, `password` varchar(256) NULL, `use_default_auth` bool NOT NULL, `mac` varchar(20) NULL, `remote_ip` varchar(16) NULL, `brand` varchar(64) NULL, `cpu` varchar(64) NULL, `memory` varchar(128) NULL, `disk` varchar(1024) NULL, `system_type` varchar(32) NULL, `system_version` varchar(8) NULL, `system_arch` varchar(16) NULL, `cabinet` varchar(32) NULL, `position` integer NULL, `number` varchar(32) NULL, `status` integer NULL, `asset_type` integer NULL, `env` integer NULL, `sn` varchar(128) NULL, `date_added` datetime NULL, `is_active` bool NOT NULL, `comment` varchar(128) NULL); (params None)
[DEBUG 2016-11-19 10:01:26,102 @ 23056] - CREATE TABLE `Cmdb_assetgroup` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE, `comment` varchar(160) NULL); (params None)
[DEBUG 2016-11-19 10:01:26,131 @ 23056] - CREATE TABLE `Cmdb_assetrecord` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `username` varchar(30) NULL, `alert_time` datetime NOT NULL, `content` longtext NULL, `comment` longtext NULL, `asset_id` integer NOT NULL); (params None)
[DEBUG 2016-11-19 10:01:26,157 @ 23056] - CREATE TABLE `Cmdb_idc` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(32) NOT NULL, `bandwidth` varchar(32) NULL, `linkman` varchar(16) NULL, `phone` varchar(32) NULL, `address` varchar(128) NULL, `network` longtext NULL, `date_added` date NULL, `operator` varchar(32) NULL, `comment` varchar(128) NULL); (params None)
[DEBUG 2016-11-19 10:01:26,262 @ 23056] - CREATE TABLE `Cmdb_asset_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `asset_id` integer NOT NULL, `assetgroup_id` integer NOT NULL, UNIQUE (`asset_id`, `assetgroup_id`)); (params None)
[DEBUG 2016-11-19 10:01:26,309 @ 23056] - ALTER TABLE `Cmdb_asset` ADD COLUMN `idc_id` integer NULL; (params [])
[DEBUG 2016-11-19 10:01:26,316 @ 23056] - ALTER TABLE `Cmdb_asset` ALTER COLUMN `idc_id` DROP DEFAULT; (params [])
[DEBUG 2016-11-19 10:01:26,326 @ 23056] - ALTER TABLE `Cmdb_assetrecord` ADD CONSTRAINT `Cmdb_assetrecord_asset_id_19e1e7bf_fk_Cmdb_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `Cmdb_asset` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,332 @ 23056] - CREATE INDEX `Cmdb_assetrecord_51c6d5db` ON `Cmdb_assetrecord` (`asset_id`); (params [])
[DEBUG 2016-11-19 10:01:26,338 @ 23056] - ALTER TABLE `Cmdb_asset_group` ADD CONSTRAINT `Cmdb_asset_group_asset_id_34905f0_fk_Cmdb_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `Cmdb_asset` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,345 @ 23056] - ALTER TABLE `Cmdb_asset_group` ADD CONSTRAINT `Cmdb_asset_group_assetgroup_id_768ad676_fk_Cmdb_assetgroup_id` FOREIGN KEY (`assetgroup_id`) REFERENCES `Cmdb_assetgroup` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,351 @ 23056] - CREATE INDEX `Cmdb_asset_group_51c6d5db` ON `Cmdb_asset_group` (`asset_id`); (params [])
[DEBUG 2016-11-19 10:01:26,361 @ 23056] - CREATE INDEX `Cmdb_asset_group_2f088294` ON `Cmdb_asset_group` (`assetgroup_id`); (params [])
[DEBUG 2016-11-19 10:01:26,371 @ 23056] - CREATE INDEX `Cmdb_asset_0869e37a` ON `Cmdb_asset` (`idc_id`); (params [])
[DEBUG 2016-11-19 10:01:26,380 @ 23056] - ALTER TABLE `Cmdb_asset` ADD CONSTRAINT `Cmdb_asset_idc_id_71aeb26e_fk_Cmdb_idc_id` FOREIGN KEY (`idc_id`) REFERENCES `Cmdb_idc` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,410 @ 23056] - CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL); (params None)
[DEBUG 2016-11-19 10:01:26,441 @ 23056] - ALTER TABLE `django_content_type` ADD CONSTRAINT `django_content_type_app_label_3ec8c61c_uniq` UNIQUE (`app_label`, `model`); (params [])
[DEBUG 2016-11-19 10:01:26,473 @ 23056] - CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL, UNIQUE (`content_type_id`, `codename`)); (params None)
[DEBUG 2016-11-19 10:01:26,526 @ 23056] - CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(80) NOT NULL UNIQUE); (params None)
[DEBUG 2016-11-19 10:01:26,535 @ 23056] - CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL, UNIQUE (`group_id`, `permission_id`)); (params None)
[DEBUG 2016-11-19 10:01:26,588 @ 23056] - CREATE TABLE `auth_user` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime NOT NULL, `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(75) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime NOT NULL); (params None)
[DEBUG 2016-11-19 10:01:26,596 @ 23056] - CREATE TABLE `auth_user_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `group_id` integer NOT NULL, UNIQUE (`user_id`, `group_id`)); (params None)
[DEBUG 2016-11-19 10:01:26,605 @ 23056] - CREATE TABLE `auth_user_user_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `permission_id` integer NOT NULL, UNIQUE (`user_id`, `permission_id`)); (params None)
[DEBUG 2016-11-19 10:01:26,612 @ 23056] - ALTER TABLE `auth_permission` ADD CONSTRAINT `auth_permissi_content_type_id_51277a81_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,618 @ 23056] - CREATE INDEX `auth_permission_417f1b1c` ON `auth_permission` (`content_type_id`); (params [])
[DEBUG 2016-11-19 10:01:26,628 @ 23056] - ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissions_group_id_58c48ba9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,635 @ 23056] - ALTER TABLE `auth_group_permissions` ADD CONSTRAINT `auth_group_permissi_permission_id_23962d04_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,642 @ 23056] - CREATE INDEX `auth_group_permissions_0e939a4f` ON `auth_group_permissions` (`group_id`); (params [])
[DEBUG 2016-11-19 10:01:26,648 @ 23056] - CREATE INDEX `auth_group_permissions_8373b171` ON `auth_group_permissions` (`permission_id`); (params [])
[DEBUG 2016-11-19 10:01:26,654 @ 23056] - ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_user_id_24702650_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,661 @ 23056] - ALTER TABLE `auth_user_groups` ADD CONSTRAINT `auth_user_groups_group_id_30a071c9_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,667 @ 23056] - CREATE INDEX `auth_user_groups_e8701ad4` ON `auth_user_groups` (`user_id`); (params [])
[DEBUG 2016-11-19 10:01:26,673 @ 23056] - CREATE INDEX `auth_user_groups_0e939a4f` ON `auth_user_groups` (`group_id`); (params [])
[DEBUG 2016-11-19 10:01:26,678 @ 23056] - ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_permissions_user_id_7cd7acb6_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,684 @ 23056] - ALTER TABLE `auth_user_user_permissions` ADD CONSTRAINT `auth_user_user_perm_permission_id_3d7071f0_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,690 @ 23056] - CREATE INDEX `auth_user_user_permissions_e8701ad4` ON `auth_user_user_permissions` (`user_id`); (params [])
[DEBUG 2016-11-19 10:01:26,697 @ 23056] - CREATE INDEX `auth_user_user_permissions_8373b171` ON `auth_user_user_permissions` (`permission_id`); (params [])
[DEBUG 2016-11-19 10:01:26,756 @ 23056] - CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime NOT NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL, `change_message` longtext NOT NULL, `content_type_id` integer NULL, `user_id` integer NOT NULL); (params None)
[DEBUG 2016-11-19 10:01:26,763 @ 23056] - ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin__content_type_id_5151027a_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,770 @ 23056] - ALTER TABLE `django_admin_log` ADD CONSTRAINT `django_admin_log_user_id_1c5f563_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`); (params [])
[DEBUG 2016-11-19 10:01:26,778 @ 23056] - CREATE INDEX `django_admin_log_417f1b1c` ON `django_admin_log` (`content_type_id`); (params [])
[DEBUG 2016-11-19 10:01:26,783 @ 23056] - CREATE INDEX `django_admin_log_e8701ad4` ON `django_admin_log` (`user_id`); (params [])
[DEBUG 2016-11-19 10:01:26,905 @ 23056] - ALTER TABLE `django_content_type` MODIFY `name` varchar(100) NULL; (params [])
[DEBUG 2016-11-19 10:01:26,979 @ 23056] - ALTER TABLE `django_content_type` DROP COLUMN `name` CASCADE; (params [])
[DEBUG 2016-11-19 10:01:27,042 @ 23056] - ALTER TABLE `auth_permission` MODIFY `name` varchar(255) NOT NULL; (params [])
[DEBUG 2016-11-19 10:01:27,109 @ 23056] - ALTER TABLE `auth_user` MODIFY `email` varchar(254) NOT NULL; (params [])
[DEBUG 2016-11-19 10:01:27,236 @ 23056] - ALTER TABLE `auth_user` MODIFY `last_login` datetime NULL; (params [])
[DEBUG 2016-11-19 10:01:27,266 @ 23056] - CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime NOT NULL); (params None)
[DEBUG 2016-11-19 10:01:27,275 @ 23056] - CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date`); (params [])
[ERROR 2016-11-19 10:18:08,982 @ 6952] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 29, in post
    return packageResponse(ret)
  File "D:\work\redjango\Management\Cmdb\methods\common.py", line 12, in packageResponse
    json_status = json.dumps(json_status)
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AttributeError("'AssetGroup' object has no attribute 'update'",) is not JSON serializable
[ERROR 2016-11-19 10:18:25,980 @ 6952] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 29, in post
    return packageResponse(ret)
  File "D:\work\redjango\Management\Cmdb\methods\common.py", line 12, in packageResponse
    json_status = json.dumps(json_status)
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AttributeError("'AssetGroup' object has no attribute 'update'",) is not JSON serializable
[ERROR 2016-11-19 10:18:28,275 @ 6952] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 29, in post
    return packageResponse(ret)
  File "D:\work\redjango\Management\Cmdb\methods\common.py", line 12, in packageResponse
    json_status = json.dumps(json_status)
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AttributeError("'AssetGroup' object has no attribute 'update'",) is not JSON serializable
[ERROR 2016-11-19 10:18:30,923 @ 6952] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 29, in post
    return packageResponse(ret)
  File "D:\work\redjango\Management\Cmdb\methods\common.py", line 12, in packageResponse
    json_status = json.dumps(json_status)
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AttributeError("'AssetGroup' object has no attribute 'update'",) is not JSON serializable
[ERROR 2016-11-19 10:18:34,153 @ 6952] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-19 10:19:23,802 @ 14960] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-19 10:19:38,806 @ 14960] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 29, in post
    return packageResponse(ret)
  File "D:\work\redjango\Management\Cmdb\methods\common.py", line 12, in packageResponse
    json_status = json.dumps(json_status)
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AttributeError("'AssetGroup' object has no attribute 'update'",) is not JSON serializable
[ERROR 2016-11-19 10:34:29,825 @ 27300] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 140, in group_post
    ret=globals()[request.POST.get('type')](request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 102, in group_update
    ddata=json.loads(request.POST.get('newarray'))
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[ERROR 2016-11-19 10:34:58,655 @ 27300] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 29, in post
    return packageResponse(ret)
  File "D:\work\redjango\Management\Cmdb\methods\common.py", line 12, in packageResponse
    json_status = json.dumps(json_status)
  File "C:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: AttributeError("'AssetGroup' object has no attribute 'update'",) is not JSON serializable
[ERROR 2016-11-19 10:36:54,194 @ 9308] - Internal Server Error: /v1/cmdb/list/grouppost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 140, in group_post
    ret=globals()[request.POST.get('type')](request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 102, in group_update
    ddata=json.loads(request.POST.get('newarray'))
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[ERROR 2016-11-19 11:15:42,801 @ 11024] - Internal Server Error: /v1/cmdb/list/assetpost/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 186, in assetpost
    ret['status'] = e[1]
IndexError: tuple index out of range
[ERROR 2016-11-19 14:23:24,176 @ 9676] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-22 10:58:00,253 @ 9676] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 10:21:40,322 @ 7936] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 10:35:42,640 @ 8188] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 10:43:34,006 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:03:02,487 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:03:42,270 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:03:46,026 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:04:05,433 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:04:12,539 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:04:38,523 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:04:41,062 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:04:58,108 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:06:13,578 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-24 15:43:43,147 @ 1264] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 24, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 77, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[DEBUG 2016-11-24 16:41:52,605 @ 17492] - CREATE TABLE `service_register` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name_type` varchar(80) NOT NULL UNIQUE, `service_name` varchar(50) NULL, `service_start` varchar(100) NULL, `service_stop` varchar(100) NULL, `service_restart` varchar(100) NULL, `path_config` varchar(150) NULL, `path_root` varchar(150) NULL, `path_project` varchar(150) NULL, `desc` varchar(150) NULL); (params None)
[DEBUG 2016-11-24 16:41:54,667 @ 17492] - CREATE TABLE `service_register_Asset_service` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `register_id` integer NOT NULL, `asset_id` integer NOT NULL, UNIQUE (`register_id`, `asset_id`)); (params None)
[DEBUG 2016-11-24 16:41:54,668 @ 17492] - ALTER TABLE `service_register_Asset_service` ADD CONSTRAINT `service_register_Ass_register_id_393b2379_fk_service_register_id` FOREIGN KEY (`register_id`) REFERENCES `service_register` (`id`); (params [])
[DEBUG 2016-11-24 16:41:54,671 @ 17492] - ALTER TABLE `service_register_Asset_service` ADD CONSTRAINT `service_register_Asset_servic_asset_id_3d1ea093_fk_Cmdb_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `Cmdb_asset` (`id`); (params [])
[DEBUG 2016-11-24 16:41:54,671 @ 17492] - CREATE INDEX `service_register_Asset_service_ae299483` ON `service_register_Asset_service` (`register_id`); (params [])
[DEBUG 2016-11-24 16:41:54,674 @ 17492] - CREATE INDEX `service_register_Asset_service_51c6d5db` ON `service_register_Asset_service` (`asset_id`); (params [])
[ERROR 2016-11-24 17:32:42,897 @ 19564] - Internal Server Error: /v1/service/list/register/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 26, in post
    ret = Methods.get('POST').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-24 17:32:48,286 @ 19564] - Internal Server Error: /v1/service/list/register/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 22, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-24 17:35:16,772 @ 20032] - Internal Server Error: /v1/service/list/register/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\service\rests.py", line 28, in post
    ret = Methods.get('POST').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-24 18:41:10,398 @ 20532] - Internal Server Error: /v1/service/list/register/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\service\rests.py", line 23, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-25 13:51:35,299 @ 21772] - Internal Server Error: /v1/cmdb/list/groupget/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 22, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\Cmdb\methods\cmdb_fun.py", line 75, in group_get
    ret['data']=globals()[request.GET.get('name')](group_id)
KeyError: None
[ERROR 2016-11-25 13:51:58,690 @ 21772] - Internal Server Error: /v1/cmdb/list/typelist/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 22, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-25 13:52:08,926 @ 21772] - Internal Server Error: /v1/service/list/register/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\service\rests.py", line 23, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-25 13:52:19,358 @ 21772] - Internal Server Error: /v1/cmdb/list/typelist/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 22, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-25 13:52:33,974 @ 21772] - Internal Server Error: /v1/cmdb/list/type_list、/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 22, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-25 13:52:39,065 @ 21772] - Internal Server Error: /v1/cmdb/list/type_list/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 22, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-25 13:53:31,854 @ 13880] - Internal Server Error: /v1/cmdb/list/type_list/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\Cmdb\rests.py", line 22, in get
    ret = Methods.get('GET').get(fun)(request)
TypeError: 'NoneType' object is not callable
[ERROR 2016-11-25 15:19:20,874 @ 29836] - Internal Server Error: /v1/service/list/query/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python27\lib\site-packages\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\work\redjango\Management\service\rests.py", line 23, in get
    ret = Methods.get('GET').get(fun)(request)
  File "D:\work\redjango\Management\service\service.py", line 52, in query_host
    sys['host']=map((lambda x:x.name),service.Asset_service.all())
  File "D:\work\redjango\Management\service\service.py", line 52, in <lambda>
    sys['host']=map((lambda x:x.name),service.Asset_service.all())
AttributeError: 'Asset' object has no attribute 'name'
